version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: TwitchLib
    versions:
    - 3.1.1
